### PR TITLE
Upgrade provider to track v4.

### PR DESCRIPTION
**Pull request by strictlyd**
Upgrades the provider to track v4

See: https://github.com/hashicorp/terraform-cdk/issues/833

### CODE REVIEW

**Comment by skorfmann** [comment]
Cool - thank you!

**Comment by skorfmann** [comment]
Can you please run `npx projen` to reflect the changes in the rest of the repo?

Also, please make sure to add something like `BREAKING CHANGE: The provider version got bumped from 2 to 4` to one of your commit bodies. This should automatically bump the version accordingly.

**Comment by strictlyd** [comment]
Thanks, updated.

**Comment by strictlyd** [comment]
Hmm it doesn't look like the latest version contains v4 changes. Does it require a PR from the upstream repo to trigger?

**Comment by skorfmann** [comment]
Yes - sorry for the confusion, I forgot that a `yarn fetch` would have been necessary to actually update the code. However, this PR https://github.com/terraform-cdk-providers/cdktf-provider-github/pull/403 actually fixed it.

**Pull request merged**
